spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/foobardb
    username: postgres
    password: password
  jpa:
    database-platform:  "org.hibernate.dialect.PostgreSQLDialect"
  flyway:
    baseline-on-migrate: true


