spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/test?zeroDateTimeBehavior=round
    username: postgres
    password: password
    hikari:
      auto-commit: false
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        formatSql: true
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    show-sql: true

